import { describe, expect, test } from "bun:test";
import {
  buildPresignedUrl,
  deriveKeyId,
  hashToken,
  PRESIGN_HTTP_METHODS,
  sign,
} from "../presign";

// The SDK cannot import the server (that is the whole point of an offline
// signer), so every expected value below was generated by the SERVER's
// src/lib/presign.ts and frozen here. If a value changes, one side has drifted
// and presigned URLs minted by this SDK will 401 against the server.
//
// Cross-checked at authoring time against Bun.CryptoHasher for hashToken,
// deriveKeyId, sign and buildPresignedUrl, and end-to-end against a live
// server: offline-minted URL -> 200; expired -> 401 PRESIGNED_EXPIRED;
// tampered signature -> 401 INVALID_API_KEY.

const TOKEN = "buns3_anchor_token_for_sdk_tests";
const TOKEN_HASH =
  "6593562501ae542ffe032efe6606f5248ee7d168bdec28f6aba28e75808312e3";
const KEY_ID =
  "3378632a177dda59c880194f86442228287dbbd08f8339dece9ba5d972ddaf75";

type Vector = [
  method: (typeof PRESIGN_HTTP_METHODS)[number],
  bucket: string,
  key: string,
  expires: number,
  sig: string,
];

const VECTORS: Vector[] = [
  ["GET", "dev", "hello.txt", 1788464027, "aedaa96f8c262ce87cefe3e590994cb6efad3f58ac85a889ae2b21a57fb63905"],
  // a key with a space and a percent — the canonical string signs the RAW key
  ["PUT", "dev", "a/b c/100%.txt", 0, "b0fd174a1bbf752e2920608f5560227e8157a03b004c4ee2ff2bf8718e754190"],
  // empty segment, and the maximum legal expires (a format bound, not a TTL)
  ["DELETE", "dev", "a//b", 999999999999, "52fac463712ae671082519d553aba01df338008639c7dce80cfb80b18a8ed09c"],
  ["HEAD", "dev", "sdk/ü/日本.txt", 1, "06dee4b26ab7e889905b2cada41e65ae07d20c931744fe8b569f6d495f8f5e6f"],
];

describe("hashToken", () => {
  test("sha256 hex — the cross-implementation anchor vector", async () => {
    // The same constant the SERVER's presign test asserts. Both implementations
    // must reproduce it; this is the single value tying them together.
    expect(await hashToken("hello")).toBe(
      "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
    );
  });

  test("matches the server for the test token", async () => {
    expect(await hashToken(TOKEN)).toBe(TOKEN_HASH);
  });

  test.each([
    ["", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],
    ["ü", "607474ca475a9724d7360aba71a56d5df77e61350e3f724cfa1f46e857e2d85f"],
    ["🙂", "d06f1525f791397809f9bc98682b5c13318eca4c3123433467fd4dffda44fd14"],
  ])("hashes %j as the server does (UTF-8 encoded, not Latin-1)", async (token, expected) => {
    expect(await hashToken(token)).toBe(expected);
  });

  test("always returns 64 lowercase hex chars (padStart on every byte)", async () => {
    // A byte like 0x0a rendered as "a" instead of "0a" would shift the whole
    // string and silently invalidate every signature.
    for (const t of ["", "a", "hello", TOKEN, "🙂"]) {
      expect(await hashToken(t)).toMatch(/^[0-9a-f]{64}$/);
    }
  });
});

describe("deriveKeyId", () => {
  test("matches the server's derived key id", async () => {
    expect(await deriveKeyId(TOKEN_HASH)).toBe(KEY_ID);
  });

  test("is deterministic", async () => {
    expect(await deriveKeyId(TOKEN_HASH)).toBe(await deriveKeyId(TOKEN_HASH));
  });

  test("is a public fingerprint, never the hash itself", async () => {
    expect(await deriveKeyId(TOKEN_HASH)).not.toBe(TOKEN_HASH);
    expect(await deriveKeyId(TOKEN_HASH)).toMatch(/^[0-9a-f]{64}$/);
  });

  test("different hashes derive different ids", async () => {
    const other = await hashToken("some other token");
    expect(await deriveKeyId(other)).not.toBe(KEY_ID);
  });
});

describe("sign", () => {
  test.each(VECTORS)(
    "%s /%s/%j expires=%d matches the server's signature",
    async (method, bucket, key, expires, expected) => {
      expect(await sign({ tokenHash: TOKEN_HASH, method, bucket, key, expires })).toBe(
        expected,
      );
    },
  );

  test("signs the RAW key — never the URL-encoded form", async () => {
    // Signing the encoded key is the mint-side double-encode bug: the server
    // percent-decodes the path before verifying, so the two would never agree.
    const raw = await sign({
      tokenHash: TOKEN_HASH,
      method: "PUT",
      bucket: "dev",
      key: "a/b c/100%.txt",
      expires: 0,
    });
    const encoded = await sign({
      tokenHash: TOKEN_HASH,
      method: "PUT",
      bucket: "dev",
      key: "a/b%20c/100%25.txt",
      expires: 0,
    });
    expect(raw).not.toBe(encoded);
    expect(raw).toBe(VECTORS[1]![4]);
  });

  const base = {
    tokenHash: TOKEN_HASH,
    method: "GET",
    bucket: "dev",
    key: "hello.txt",
    expires: 1788464027,
  } as const;

  test.each([
    ["method", { method: "HEAD" }],
    ["bucket", { bucket: "other" }],
    ["key", { key: "hello.txt " }],
    ["expires", { expires: 1788464028 }],
    ["tokenHash", { tokenHash: "0".repeat(64) }],
  ] as const)("changing %s changes the signature", async (_, patch) => {
    // Every field is bound into the canonical string: a URL signed for GET
    // cannot be replayed as PUT, nor moved to another bucket/key/expiry.
    expect(await sign({ ...base, ...patch })).not.toBe(VECTORS[0]![4]);
  });

  test("is deterministic (no nonce, so URLs are reproducible)", async () => {
    expect(await sign(base)).toBe(await sign(base));
  });
});

describe("buildPresignedUrl", () => {
  const parts = { keyId: KEY_ID, expires: 1788464027, sig: "deadbeef" };

  test("encodes the key per segment, matching the server's Location spelling", async () => {
    expect(buildPresignedUrl("http://x", "dev", "a/b c/100%.txt", parts)).toBe(
      `http://x/dev/a/b%20c/100%25.txt?keyId=${KEY_ID}&expires=1788464027&sig=deadbeef`,
    );
  });

  test("preserves an empty segment (a//b is a different object than a/b)", () => {
    expect(buildPresignedUrl("http://x", "dev", "a//b", parts)).toContain(
      "/dev/a//b?",
    );
  });

  test("assembles by string concatenation — a base path is NOT normalized away", () => {
    // new URL() would resolve dot-segments and discard a base path; the base
    // must be an ORIGIN, and the builder must not silently rewrite it.
    expect(buildPresignedUrl("http://x/base", "dev", "k", parts)).toStartWith(
      "http://x/base/dev/k?",
    );
  });

  test("puts the three params in a fixed order", () => {
    const url = buildPresignedUrl("http://x", "dev", "k", parts);
    expect(url.slice(url.indexOf("?"))).toBe(
      `?keyId=${KEY_ID}&expires=1788464027&sig=deadbeef`,
    );
  });
});

describe("PRESIGN_HTTP_METHODS", () => {
  test("mirrors the server's presign method set exactly", () => {
    // The server's methodCapabilityMap is `satisfies`-total over these four:
    // GET/HEAD -> read, PUT/DELETE -> write. POST and PATCH are NOT presignable.
    expect([...PRESIGN_HTTP_METHODS].sort()).toEqual([
      "DELETE",
      "GET",
      "HEAD",
      "PUT",
    ]);
  });
});
